language: bash

before_install:
   - sudo apt-get update && sudo apt-get install -y shellcheck

script:
  - ls -l
  - shellcheck vsftpd.sh
  - bash vsftpd.sh
  - shellcheck nfs_s.sh
  - bash nfs_s.sh
  - shellcheck nfs_c.sh
  - bash nfs_c.sh
  - shellcheck dhcp.sh
  - bash dhcp.sh 

notifications:
  email:
    on_success: never
