language: bash

before_install:
   - sudo apt-get update && sudo apt-get install -y shellcheck

script:
  - ls -l
  - shellcheck vsftpd.sh
  - sudo bash vsftpd.sh
  - shellcheck nfs_s.sh
  - sudo bash nfs_s.sh
  - shellcheck nfs_c.sh
  - sudo bash nfs_c.sh
  - shellcheck dhcp.sh
  - sudo bash dhcp.sh
  - shellcheck smbd.sh
  - sudo bash smbd.sh  

notifications:
  email:
    on_success: never
